# Generated by Django 4.2.1 on 2023-09-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0003_alter_userprofile_email_alter_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('description', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('party_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EVS.election')),
            ],
        ),
    ]
