# Generated by Django 4.2.1 on 2023-11-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0005_voteblocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteblocks',
            old_name='blockchain_code',
            new_name='Block_Hash',
        ),
        migrations.RemoveField(
            model_name='voteblocks',
            name='previous_hash',
        ),
    ]
