# Generated by Django 4.2.1 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0006_rename_blockchain_code_voteblocks_block_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_voted_in_election',
            field=models.BooleanField(default=False),
        ),
    ]
