# Generated by Django 4.2.1 on 2023-11-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVS', '0007_userprofile_has_voted_in_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_voted_in_election',
        ),
    ]
